"""Initial migration

Revision ID: 287c1dca2525
Revises: 
Create Date: 2025-10-20 14:18:04.195778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287c1dca2525'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parts', sa.JSON(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('is_compatible', sa.Boolean(), nullable=True),
    sa.Column('compatibility_issues', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compatibility_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_type_1', sa.String(length=50), nullable=False),
    sa.Column('part_type_2', sa.String(length=50), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('rule_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('part_type', sa.String(length=50), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parts')
    op.drop_table('compatibility_rules')
    op.drop_table('builds')
    # ### end Alembic commands ###
